import { chromium } from '@playwright/test';
const browser=await chromium.launch({headless:true,channel:'chrome',args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173');await page.waitForFunction(()=>!!window.__fishslop,{timeout:30000});
await page.screenshot({path:'artifacts/welcome.png'});
console.log('initial',await page.evaluate(()=>window.__fishslop.status()));
await page.getByRole('button',{name:"Let's dive in"}).click();
const initialZ=await page.evaluate(()=>window.__fishslop.snapshot().sub.z);
await page.keyboard.down('KeyW');await page.waitForTimeout(900);await page.keyboard.up('KeyW');
if(await page.evaluate(()=>window.__fishslop.snapshot().sub.z)>=initialZ)throw new Error('Movement failed');
await page.keyboard.down('Space');await page.waitForTimeout(1800);await page.keyboard.up('Space');
console.log('played',await page.evaluate(()=>({status:window.__fishslop.status(),food:window.__fishslop.snapshot().food.length,sub:window.__fishslop.snapshot().sub})));
await page.screenshot({path:'artifacts/playing.png'});
await page.getByRole('button',{name:'Pause game',exact:true}).click();
const time=await page.evaluate(()=>window.__fishslop.snapshot().time);await page.waitForTimeout(500);
if(await page.evaluate(()=>window.__fishslop.snapshot().time)!==time)throw new Error('Pause advanced time');
await page.getByRole('button',{name:'Back to the reef'}).click();
await page.getByRole('button',{name:'Open aquarium shop'}).click();
await page.locator('[data-buy="fish:3"]').click();
if(await page.locator('#population').textContent()!=='30')throw new Error('Fish purchase failed');
await page.reload();await page.waitForFunction(()=>!!window.__fishslop);
if(await page.locator('#population').textContent()!=='30')throw new Error('Saved population lost');
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/mobile.png'});
console.log('errors',errors);if(errors.length)throw new Error(errors.join('\n'));
await browser.close();
